import { Job } from "./types";

export const MOCK_JOBS: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    company: "Google",
    location: "Mountain View, CA",
    type: "hybrid",
    level: "senior",
    salaryMin: 180000,
    salaryMax: 280000,
    description:
      "Join Google's core search team to build next-generation search experiences. You'll work on performance-critical React applications serving billions of users, collaborating with world-class engineers to shape the future of information access.",
    requirements: [
      "5+ years of experience with React, TypeScript, and modern frontend frameworks",
      "Strong understanding of web performance optimization",
      "Experience with large-scale distributed systems",
      "BS/MS in Computer Science or equivalent experience",
    ],
    benefits: [
      "Competitive salary and equity",
      "Comprehensive health insurance",
      "Free meals and snacks",
      "On-site gym and wellness programs",
    ],
    tags: ["React", "TypeScript", "Performance", "Search"],
    postedDate: "2026-02-10",
  },
  {
    id: "2",
    title: "Full Stack Developer",
    company: "Stripe",
    location: "San Francisco, CA",
    type: "remote",
    level: "mid",
    salaryMin: 150000,
    salaryMax: 220000,
    description:
      "Build the economic infrastructure for the internet. Work on Stripe's dashboard and API products that power millions of businesses worldwide. You'll ship features that directly impact developer experience and business growth.",
    requirements: [
      "3+ years of experience with React and Node.js",
      "Experience with payment systems or financial technology",
      "Strong API design skills",
      "Familiarity with Ruby or Go is a plus",
    ],
    benefits: [
      "Remote-first culture",
      "Annual learning budget",
      "Home office stipend",
      "Generous PTO policy",
    ],
    tags: ["React", "Node.js", "Payments", "API"],
    postedDate: "2026-02-12",
  },
  {
    id: "3",
    title: "AI/ML Engineer",
    company: "OpenAI",
    location: "San Francisco, CA",
    type: "onsite",
    level: "senior",
    salaryMin: 200000,
    salaryMax: 350000,
    description:
      "Work on the cutting edge of artificial intelligence. Help build and deploy large language models that are changing how people interact with technology. Collaborate with researchers to bring AI capabilities to millions.",
    requirements: [
      "5+ years in machine learning or AI research",
      "Experience with PyTorch or TensorFlow",
      "Strong Python programming skills",
      "Published research papers preferred",
    ],
    benefits: [
      "Equity in a leading AI company",
      "World-class team and mentorship",
      "Catered meals and snacks",
      "Relocation assistance",
    ],
    tags: ["Python", "ML", "AI", "LLMs"],
    postedDate: "2026-02-08",
  },
  {
    id: "4",
    title: "Product Designer",
    company: "Figma",
    location: "New York, NY",
    type: "hybrid",
    level: "mid",
    salaryMin: 140000,
    salaryMax: 200000,
    description:
      "Design the tools that designers use every day. Shape the future of collaborative design at Figma, working on features used by millions of creative professionals worldwide.",
    requirements: [
      "3+ years of product design experience",
      "Strong portfolio demonstrating UX/UI skills",
      "Experience with design systems",
      "Familiarity with front-end development concepts",
    ],
    benefits: [
      "Creative work environment",
      "Design conference budget",
      "Flexible work schedule",
      "Stock options",
    ],
    tags: ["Design", "UX", "UI", "Figma"],
    postedDate: "2026-02-14",
  },
  {
    id: "5",
    title: "Backend Engineer",
    company: "Meta",
    location: "Menlo Park, CA",
    type: "hybrid",
    level: "senior",
    salaryMin: 190000,
    salaryMax: 300000,
    description:
      "Build infrastructure that connects billions of people. Work on distributed systems, data processing pipelines, and real-time communication platforms at unprecedented scale.",
    requirements: [
      "5+ years of backend development experience",
      "Proficiency in C++, Java, or Python",
      "Experience with distributed systems at scale",
      "Strong algorithm and data structure skills",
    ],
    benefits: [
      "RSU grants",
      "401(k) matching",
      "Wellness programs",
      "Transportation benefits",
    ],
    tags: ["Backend", "Distributed Systems", "C++", "Scale"],
    postedDate: "2026-02-11",
  },
  {
    id: "6",
    title: "DevOps Engineer",
    company: "Netflix",
    location: "Los Gatos, CA",
    type: "remote",
    level: "senior",
    salaryMin: 170000,
    salaryMax: 290000,
    description:
      "Keep the world entertained. Build and maintain infrastructure that delivers streaming content to 250M+ subscribers. Work with cutting-edge cloud technologies and open-source tools.",
    requirements: [
      "5+ years in DevOps or SRE roles",
      "Deep experience with AWS or GCP",
      "Kubernetes and container orchestration expertise",
      "Strong scripting skills (Python, Bash, Go)",
    ],
    benefits: [
      "Top-of-market compensation",
      "Unlimited PTO",
      "Free Netflix subscription",
      "Stock options",
    ],
    tags: ["DevOps", "AWS", "Kubernetes", "CI/CD"],
    postedDate: "2026-02-09",
  },
  {
    id: "7",
    title: "iOS Developer",
    company: "Apple",
    location: "Cupertino, CA",
    type: "onsite",
    level: "mid",
    salaryMin: 160000,
    salaryMax: 250000,
    description:
      "Build experiences that delight billions. Work on iOS features that define how people interact with their most personal device. Push the boundaries of what's possible with Swift and SwiftUI.",
    requirements: [
      "3+ years of iOS development experience",
      "Proficiency in Swift and SwiftUI",
      "Understanding of Apple's Human Interface Guidelines",
      "Experience with Core Data and CloudKit",
    ],
    benefits: [
      "Apple product discounts",
      "Health and wellness programs",
      "Education reimbursement",
      "Stock purchase plan",
    ],
    tags: ["iOS", "Swift", "SwiftUI", "Mobile"],
    postedDate: "2026-02-13",
  },
  {
    id: "8",
    title: "Data Scientist",
    company: "Airbnb",
    location: "San Francisco, CA",
    type: "hybrid",
    level: "mid",
    salaryMin: 145000,
    salaryMax: 220000,
    description:
      "Use data to shape the future of travel. Apply statistical modeling and machine learning to improve matching between hosts and guests, optimize pricing, and enhance the booking experience.",
    requirements: [
      "3+ years of data science experience",
      "Strong SQL and Python skills",
      "Experience with A/B testing and causal inference",
      "MS or PhD in a quantitative field",
    ],
    benefits: [
      "Travel credits",
      "Sabbatical program",
      "Learning stipend",
      "Equity compensation",
    ],
    tags: ["Data Science", "Python", "ML", "Analytics"],
    postedDate: "2026-02-07",
  },
  {
    id: "9",
    title: "Security Engineer",
    company: "Cloudflare",
    location: "Austin, TX",
    type: "remote",
    level: "senior",
    salaryMin: 165000,
    salaryMax: 245000,
    description:
      "Help build a better internet. Work on security products that protect millions of websites and applications. Analyze threats, build detection systems, and respond to security incidents at global scale.",
    requirements: [
      "5+ years of security engineering experience",
      "Experience with network security and threat modeling",
      "Knowledge of cryptography and PKI",
      "Familiarity with Go or Rust",
    ],
    benefits: [
      "Remote-first culture",
      "Quarterly team offsites",
      "Professional development budget",
      "Comprehensive benefits",
    ],
    tags: ["Security", "Network", "Go", "Infrastructure"],
    postedDate: "2026-02-06",
  },
  {
    id: "10",
    title: "Junior Software Engineer",
    company: "Vercel",
    location: "San Francisco, CA",
    type: "remote",
    level: "junior",
    salaryMin: 100000,
    salaryMax: 150000,
    description:
      "Join the team behind Next.js and Vercel's deployment platform. Help build tools that millions of developers use every day to ship their web applications. Great opportunity for early-career engineers.",
    requirements: [
      "0-2 years of professional experience",
      "Familiarity with React and Next.js",
      "Understanding of web fundamentals (HTML, CSS, JS)",
      "Passion for developer tools and open source",
    ],
    benefits: [
      "Fully remote work",
      "Equipment budget",
      "Learning and development funds",
      "Flexible schedule",
    ],
    tags: ["Next.js", "React", "TypeScript", "DX"],
    postedDate: "2026-02-15",
  },
  {
    id: "11",
    title: "Engineering Manager",
    company: "Shopify",
    location: "Toronto, ON",
    type: "remote",
    level: "lead",
    salaryMin: 180000,
    salaryMax: 260000,
    description:
      "Lead a team of talented engineers building commerce infrastructure. Drive technical strategy, mentor engineers, and ship features that empower millions of merchants worldwide.",
    requirements: [
      "7+ years of software engineering experience",
      "2+ years of engineering management experience",
      "Experience with e-commerce or platform engineering",
      "Strong communication and leadership skills",
    ],
    benefits: [
      "Remote-first company",
      "Shopify stock grants",
      "Home office stipend",
      "Flexible work hours",
    ],
    tags: ["Management", "E-commerce", "Leadership", "Platform"],
    postedDate: "2026-02-05",
  },
  {
    id: "12",
    title: "React Native Developer",
    company: "Discord",
    location: "San Francisco, CA",
    type: "hybrid",
    level: "mid",
    salaryMin: 140000,
    salaryMax: 210000,
    description:
      "Build the mobile experiences that connect millions of communities. Work on Discord's React Native apps used by 200M+ monthly active users for voice, video, and text communication.",
    requirements: [
      "3+ years of React Native experience",
      "Experience with real-time communication features",
      "Strong JavaScript/TypeScript skills",
      "Experience with native module development",
    ],
    benefits: [
      "Gaming-friendly culture",
      "Nitro subscription",
      "Mental health benefits",
      "Equity package",
    ],
    tags: ["React Native", "Mobile", "TypeScript", "Real-time"],
    postedDate: "2026-02-14",
  },
  {
    id: "13",
    title: "Platform Engineer",
    company: "Datadog",
    location: "New York, NY",
    type: "hybrid",
    level: "senior",
    salaryMin: 175000,
    salaryMax: 270000,
    description:
      "Build the observability platform trusted by thousands of companies. Work on high-throughput data ingestion, processing, and visualization systems handling trillions of data points per day.",
    requirements: [
      "5+ years of backend/platform engineering experience",
      "Experience with Go, Python, or Java",
      "Knowledge of distributed systems and databases",
      "Experience with observability or monitoring tools",
    ],
    benefits: [
      "Competitive compensation",
      "Stock options",
      "Learning budget",
      "Team events",
    ],
    tags: ["Go", "Platform", "Observability", "Distributed"],
    postedDate: "2026-02-10",
  },
  {
    id: "14",
    title: "Frontend Engineer",
    company: "Linear",
    location: "San Francisco, CA",
    type: "remote",
    level: "mid",
    salaryMin: 140000,
    salaryMax: 200000,
    description:
      "Build beautifully crafted software tools. Help create the issue tracker that engineering teams love. Focus on performance, polish, and delightful user experiences.",
    requirements: [
      "3+ years of frontend development experience",
      "Expert-level React and TypeScript skills",
      "Eye for design and attention to detail",
      "Experience with real-time collaborative features",
    ],
    benefits: [
      "Remote-first",
      "Equipment budget",
      "Health benefits",
      "Equity",
    ],
    tags: ["React", "TypeScript", "Design", "Performance"],
    postedDate: "2026-02-13",
  },
  {
    id: "15",
    title: "Machine Learning Engineer",
    company: "Anthropic",
    location: "San Francisco, CA",
    type: "hybrid",
    level: "senior",
    salaryMin: 220000,
    salaryMax: 380000,
    description:
      "Help build safe and beneficial AI systems. Work on training, fine-tuning, and deploying large language models. Collaborate with researchers to develop novel approaches to AI alignment.",
    requirements: [
      "5+ years of ML engineering experience",
      "Experience training large-scale models",
      "Proficiency in Python and ML frameworks",
      "Understanding of transformer architectures",
    ],
    benefits: [
      "Mission-driven work",
      "Competitive equity",
      "Health and dental",
      "Professional development",
    ],
    tags: ["ML", "Python", "AI Safety", "LLMs"],
    postedDate: "2026-02-11",
  },
];
